:experimental:
:commandkey: &#8984;
:toc: macro
:source-highlighter: highlight.js

= Micro Frontends for Java Microservices

This script shows you how to build a microservices and micro frontends architecture with JHipster. You'll build a gateway with Spring Cloud Gateway. Then, you'll create a blog microservice and a store microservice, each with its own database. Each app will also contain a micro frontend.

**Prerequisites**:

- https://sdkman.io/[Java] 17+
- https://nodejs.com/[Node.js] 20+
- https://www.docker.com/products/docker-desktop/[Docker Desktop]
- https://www.jhipster.tech/installation/[JHipster] 8

toc::[]

== Micro frontends in action with JHipster

. Install JHipster 8:
+
[source,shell]
----
npm i -g generator-jhipster@8
----

. Run the following command to create a new directory for your micro frontends project:
+
[source,shell]
----
take micro-frontends-jhipster
----

. Create a `reactive-mf.jdl` file with the following contents:
+
[source,jdl]
----
application {
  config {
    baseName gateway
    reactive true
    packageName org.jhipster.gateway
    applicationType gateway
    authenticationType oauth2
    buildTool gradle
    clientFramework react
    clientTheme quartz
    clientThemeVariant dark
    prodDatabaseType postgresql
    serviceDiscoveryType consul
    testFrameworks [cypress]
    microfrontends [blog, store]
  }
}

application {
  config {
    baseName blog
    reactive true
    packageName org.jhipster.blog
    applicationType microservice
    authenticationType oauth2
    buildTool gradle
    clientFramework react
    databaseType neo4j
    enableHibernateCache false
    serverPort 8081
    serviceDiscoveryType consul
    testFrameworks [cypress]
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store
    reactive true
    packageName org.jhipster.store
    applicationType microservice
    authenticationType oauth2
    buildTool gradle
    clientFramework react
    databaseType mongodb
    enableHibernateCache false
    serverPort 8082
    serviceDiscoveryType consul
    testFrameworks [cypress]
  }
  entities Product
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required
  price BigDecimal required min(0)
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User with builtInEntity
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

deployment {
  deploymentType docker-compose
  serviceDiscoveryType consul
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
}

deployment {
  deploymentType kubernetes
  appsFolders [gateway, blog, store]
  clusteredDbApps [store]
  kubernetesNamespace demo
  kubernetesUseDynamicStorage true
  kubernetesStorageClassName ""
  serviceDiscoveryType consul
  dockerRepositoryName "mraible"
}
----
+
TIP: The https://plugins.jetbrains.com/plugin/19697-jhipster-jdl[JHipster JDL Plugin] is a handy tool for working with JDL files.

=== Build Java microservices with Spring Boot

. To generate a microservices architecture with micro frontend support, run the following command:
+
[source,shell]
----
jhipster jdl reactive-mf.jdl --monorepository --workspaces
----

. If you want to use Angular, append `--client-framework angular` to override the JDL value:
+
[source,shell]
----
--client-framework angular
----

. If you'd rather try out Vue, use the following:
+
[source,shell]
----
--client-framework vue
----

=== Run your reactive Spring Boot microservices

. When the process is complete, cd into the `gateway` directory and run `./gradlew` (or `npm run app:start` if you prefer npm commands).

. Open the root directory in IntelliJ IDEA and view each project's code structure.

. Open your favorite browser to `\http://localhost:8080`, and log in with the credentials displayed on the page.

. Show missing links in entities menu.

. Start the `blog` by opening a terminal and navigating to its directory. Then, start the app with Gradle.
+
[source,shell]
----
./gradlew
----

. Open a new terminal and do the same for the `store` microservice.

. Verify everything is started using Consul at `\http://localhost:8500`.

. Refresh the gateway app to see menu items.

=== Zero turnaround development that sparks joy

What if you want to work on the UI and have zero turnaround that sparks joy? ✨🤗

. In the gateway app, run `npm start`. This command will run the UI on a web server, open a browser window to `\http://localhost:9000`, and use https://browsersync.io/[Browsersync] to keep your browser in sync with your code.

. Modify the code in `gateway/src/main/webapp/app/modules/home/home.tsx` to make a quick change. For example, add the following HTML below the `<h1>`.
+
[source,html]
----
<h2 className="text-primary">
  Hi, I'm a quick edit!
</h2>
----

. You'll see this change immediately appear within your browser. Remove it, and it'll disappear right away too.

. Open another terminal, navigate into the `store` directory, and run `npm start`.

. Modify files in the `store/src/main/webapp/app/entities/store/product` directory, and you'll see the changes in your browser immediately.
+
For example, change the wrapper `<div>` in `product.tsx` to have a background color:
+
[source,html]
----
<div className="bg-info">
----
+
The UI will change before you can kbd:[Cmd+Tab] back to your browser.

NOTE: The backend has quick turnaround abilities too, thanks to https://docs.spring.io/spring-boot/docs/current/reference/html/using.html#using.devtools[Spring Boot devtools]. If you modify a backend class, recompiling it will cause Spring Boot to reload your component lickety-split. It's pretty slick!

=== A look under the hood of micro frontends

When you're learning concepts like micro frontends, it's often helpful to look at the code that makes things work.

The gateway's `webpack.microfrontend.js` handles specifying the shared dependencies and components between apps. The `src/main/webapp/app/shared/layout/menus/entities.tsx` file contains the menu items for each micro frontend.

The blog's `webpack.microfrontend.js` looks similar, except that it exposes its `remoteEntry.js`, menu items, and routes.

== Architecture as Code

Each project has a `TestStructureTest.java` class that continuously tests the architecture with [ArchUnit](https://www.archunit.org/).

== Build and run with Docker

. Build Docker images for each application by running the following command from the root directory.
+
[source,shell]
----
npm run java:docker:arm64
----
+
[TIP]
====
If you're not using Apple Silicon, drop the `:arm64`:

[source,shell]
----
npm run java:docker
----
====

. Navigate to the `docker-compose` directory, stop the existing containers, then start all the containers.
+
[source,shell]
----
cd docker-compose
docker stop $(docker ps -a -q);
docker compose up
----

. To make Keycloak work, you must add the following line to your hosts file (`/etc/hosts` on Mac/Linux, `c:\Windows\System32\Drivers\etc\hosts` on Windows).
+
----
127.0.0.1  keycloak
----

. Prove everything works at `\http://localhost:8500`

. Run Cypress e2e tests from the root directory:
+
[source,shell]
----
npm run e2e -ws
----

== Switch identity providers

JHipster ships with Keycloak when you choose OAuth 2.0 / OIDC as the authentication type. However, you can easily change it to another identity provider, like Auth0 or Okta!

See https://github.com/oktadev/auth0-micro-frontends-jhipster-example/blob/main/demo.adoc#switch-identity-providers[this demo script] or https://www.jhipster.tech/security/#oauth2[JHipster's OAuth 2.0 documentation] for additional information.

== Deploy with Kubernetes

The JDL you used to generate this microservices stack has a section at the bottom for deploying to Kubernetes.

----
deployment {
  deploymentType kubernetes
  appsFolders [gateway, blog, store]
  clusteredDbApps [store]
  kubernetesNamespace demo
  kubernetesUseDynamicStorage true
  kubernetesStorageClassName ""
  serviceDiscoveryType consul
  dockerRepositoryName "mraible"
}
----

If you have a Kubernetes cluster created, you can deploy to its `demo` namespace using the following command.

[source,shell]
----
./kubectl-apply.sh -f
----

== Have fun with Micro Frontends and JHipster!

I hope you enjoyed this demo, and it helped you understand how to build better microservice architectures with micro frontends.

☕️ Find the code on GitHub: https://github.com/mraible/jhipster-micro-frontends[@mraible/jhipster-micro-frontends]

🤓 Read about it on the Auth0 blog: https://auth0.com/blog/micro-frontends-for-java-microservices/[Micro Frontends for Java Microservices]
