apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-config-loader
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-config-loader
  template:
    metadata:
      labels:
        app: consul-config-loader
    spec:
      containers:
        - name: consul-config-loader
          image: jhipster/consul-config-loader:v0.4.1
          imagePullPolicy: IfNotPresent
          env:
            - name: INIT_SLEEP_SECONDS
              value: "5"
            - name: CONSUL_URL
              value: consul-headless.demo.svc.cluster.local
            - name: CONSUL_PORT
              value: "8500"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: application-config
