# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: store
services:
  mongodb:
    image: mongo:8.0.0
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:27017:27017
    command: mongos --configdb csvr/store-mongodb-config --bind_ip 0.0.0.0
  mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --shardsvr --replSet rs1
  mongodb-config:
    image: mongo:8.0.0
    container_name: store-mongodb-config
    command: mongod --configsvr --dbpath /data/db --replSet csvr
